# Generated by Django 4.1.7 on 2023-03-01 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0005_following_follower"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="following",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="follower",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Follower",
        ),
        migrations.DeleteModel(
            name="Following",
        ),
    ]
