# Generated by Django 4.1.7 on 2023-03-01 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SocialMedia",
            "0006_remove_following_user_user_follower_user_following_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
        migrations.AddField(
            model_name="user",
            name="follower",
            field=models.ManyToManyField(
                null=True, related_name="user_follower", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                null=True, related_name="user_following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
