# Generated by Django 4.1.5 on 2023-03-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0008_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="receiver",
        ),
    ]
