# Generated by Django 4.1.5 on 2023-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0011_reaction_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dislike",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
    ]
