# Generated by Django 4.1.5 on 2023-03-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0013_remove_post_dislike_remove_post_like_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reaction",
                to="SocialMedia.post",
            ),
        ),
    ]
